### PR TITLE
 Dependencies update to info security improvement

### PR DESCRIPTION
**Pull request by felipo**
Dependencies update to info security improvement  
Based on: https://david-dm.org/twelve-net-co/seanjs

### CODE REVIEW

**Comment by Massad** [comment]
It seems that you didn't update them all. Also you changed links in README to **twelve-net-co** instead of **seanjs-stack**

If we wanna do it, we must update all packages with full test.

**Comment by felipo** [comment]
@Massad, done!

**Comment by Massad** [comment]
Need to fix the build. Will get back to you on that.

**Comment by Massad** [comment]
Need to fix the build. Will get back to you on that.

@felipo thanks for the update and heads up!

**Comment by felipo** [comment]
Your welcome @Massad

**Pull request merged**
